feat: add envs create-from-repo subcommand
cdr/coder-cli pull request #212
Opened 2021-01-07 08:43 UTC by kylecarbs

![image](https://user-images.githubusercontent.com/7122116/103871005-53b05380-5081-11eb-8bdf-fed6e9a6e055.png)

2021-01-07 16:29 UTC, cmoog requested changes

2021-01-07 16:29 UTC, cmoog commented on internal/cmd/envs.go
> +				return xerrors.New("org is required for multi-org members")
```suggestion
				return xerrors.New("--org flag is required for multi-org members")
```

2021-01-07 16:29 UTC, cmoog commented on internal/cmd/envs.go
> +				org = orgs[0].Name
This get's all organizations in the deployment. We need to filter by orgs of which the user is a member. Use `lookupUserOrgs`.

2021-01-07 16:29 UTC, cmoog commented on internal/cmd/envs.go
> +	_ = cmd.MarkFlagRequired("image")
```suggestion
```

2021-01-07 16:29 UTC, cmoog commented on internal/cmd/envs.go
> +	cmd.Flags().StringVarP(&org, "org", "o", "", "name of the organization the environment should be created under.")
I'm not a fan of "o" as a shorthand given that it can conflict with `--output` in other cases. But I know we have this in other places so your call.

2021-01-26 03:09 UTC, cmoog approved these changes
🚀

2021-01-26 03:09 UTC, cmoog commented on internal/cmd/envs.go
> +		Args:   cobra.ExactArgs(1),
Use `xcobra.ExactArgs(1)`... it provides a much nicer error message.

2021-01-26 03:09 UTC, cmoog commented on coder-sdk/env.go
> +// Template is used to configure a new environment from a repo.
This will show up in the `coder-sdk` godoc, so maybe we should include an `alpha` note in the doc comment.

2021-01-26 03:44 UTC, sreya commented
```
--- starting integration tests
ok  	cdr.dev/coder-cli/ci/integration	186.794s
```

2021-01-26 03:49 UTC, merged